# Generated by Django 4.2.13 on 2024-06-08 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Колчество ингридиента не может быть меньше 1'), django.core.validators.MaxValueValidator(200, 'Вы уверены что необходимо такое колиество ингридиента?')], verbose_name='Количество'),
        ),
    ]
