# Generated by Django 4.2.13 on 2024-06-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='color',
        ),
    ]
