# Generated by Django 4.2.13 on 2024-06-08 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Ваше блюдо уже готово!'), django.core.validators.MaxValueValidator(200, 'Очень долго ждать...')], verbose_name='Время приготовления'),
        ),
    ]
