# Generated by Django 4.2.13 on 2024-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
