# Generated by Django 4.2.13 on 2024-06-09 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_amountingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингридиентов не может быть меньше 1')], verbose_name='Количество'),
        ),
    ]
