# Generated by Django 4.2.13 on 2024-06-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique favorite recipe for user',
        ),
    ]
