# Generated by Django 4.2.13 on 2024-06-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_ingredients_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
