# Generated by Django 4.2.13 on 2024-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
