# Generated by Django 4.2.13 on 2024-06-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_short_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_id',
            new_name='short_link',
        ),
    ]
