# Generated by Django 4.2.13 on 2024-06-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribes',
            new_name='Subscribe',
        ),
    ]
